name = "LightsheetDeconv"
uuid = "6af48ca6-4625-4142-84c3-eaff405e0c6a"
authors = ["Yueyang Feng<yueyang.f.de@gmail.com>"]
version = "1.0.0-DEV"

[compat]
julia = "1.6.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
